### ISSUE TITLE
How to prevent plugin execution entirely?

### ISSUE THREAD

**Issue by leonderijke** [deltamualpha/metalsmith-if#1]
Currently, plugins are instantiated, regardless of the conditional. For example, when I pair `metalsmith-if` with `metalsmith-watch`'s `livereload` option, the livereload server is started, even if the conditional is falsy:

``` js
.use(msIf(false, watch({livereload: true})))
```

console output:

```
[metalsmith-watch] ✓ Live reload server started on port: 35729
```

Is there a way to prevent the plugin from executing/instantiating entirely?

**Comment by deltamualpha** [comment]
Ah, yes, I should document this since I ran into it as well.

Something in `metalsmith-watch` starts the server immediately upon first parsing (which this plugin doesn't have any control over). If you're using some logic to set the conditional in metalsmith-if, pass that variable to the `livereload` prop as well in the options object and that message should disappear.

But to answer your question: no, there's no way to keep plugins from being instantiated entirely that I know of.

**Comment by leonderijke** [comment]
Thanks!

**Comment by deltamualpha** [comment]
documented: https://github.com/deltamualpha/metalsmith-if/commit/87a3b37205cd9d2db4520d1575aa21b4e4d54d2d

**Comment by Noamyoungerm** [comment]
How about being able to accept a parameter of the form

```
function() {
   return plugin(opts);
}
```

and only executing it if the result of the conditional is true? It should be possible to detect whether a given function is a wrapper or the actual plugin - execute the function once, and if the result returned is a function, execute that again. Plugins generally (always?) don't return anything.

**Comment by deltamualpha** [comment]
Hmm, blindly attempting to execute plugins seems like a good way to cause havoc. Imagine if `metalsmith-watch` defaulted to having `livereload: true` -- then we'd instantiate the livereload server ourselves and probably hang, if it didn't just throw an error. If you can come up with a safe way to do it, however, I'd consider a pull request.

**Comment by xzyfer** [comment]
For reference to work around this I do the following

``` js
var when = require('metalsmith-if');

   ...
  .use(when(condition, function() {
      plugin()
  }))
  ...
```
